#!/bin/sh
set -ex
cd "$(dirname "$0")"

. ./.env

export HOST="$HOST"
export RETICULUM_SOCKET_SERVER="$RETICULUM_SOCKET_SERVER"
export CORS_PROXY_SERVER="$CORS_PROXY_SERVER"
export NON_CORS_PROXY_DOMAINS="$NON_CORS_PROXY_DOMAINS"
export BASE_ASSETS_PATH="$BASE_ASSETS_PATH"
export RETICULUM_SERVER="$RETICULUM_SERVER"
export POSTGREST_SERVER=""
export ITA_SERVER=""
export INTERNAL_HOSTNAME="$INTERNAL_HOSTNAME"
export HOST_IP="0.0.0.0"

npm run dev
